import { tokenize } from './src/lexer.js';
import { parse } from './src/parser.js';
import { validate } from './src/validate.js';
import { loadTargets, getTarget, getTargetNames } from './src/codegen/targets.js';

await loadTargets();

function formatParam(param) {
  const opt = param.defaultValue ? '?' : '';
  if (!param?.type) return `Anything${opt}`;
  if (param.positional) return `${param.type}${opt}`;
  return `:${param.name} ${param.type}${opt}`;
}

function formatReplyField(field, index) {
  if (!field?.type) return `:arg${index + 1} Anything`;
  if (field.positional) return field.type;
  if ('sigil' in field) return `:${field.sigil} ${field.type}`;
  if (field.key !== undefined) return `:${field.key} ${field.type}`;
  return `:arg${index + 1} ${field.type}`;
}

function formatPublicFnSig(fn) {
  const input = fn.params.map(formatParam).join(', ');
  const reply = fn.body.find(stmt => stmt.type === 'Reply');
  if (!reply) return `(${input}) -> .`;
  const output = reply.fields.map(formatReplyField).join(', ');
  return `(${input}) -> (${output})`;
}

function formatConstructorSig(actor) {
  const input = actor.params.map(formatParam).join(', ');
  const methods = actor.functions.filter(f => f.name && f.name.startsWith('@'));
  const methodLines = methods.map(fn => {
    const name = fn.name.replace(/^@/, '');
    const sig = formatPublicFnSig(fn);
    return `    ${name}: ${sig}`;
  });
  return `<${input}> -> {\n${methodLines.join('\n')}\n  }`;
}

function buildServiceDocument(ast) {
  const lines = [];
  for (const actor of ast.actors) {
    // Public constructor: actor with @-prefixed name
    if (actor.name && actor.name.startsWith('@')) {
      const name = actor.name.replace(/^@/, '');
      lines.push(`${name}: ${formatConstructorSig(actor)}`);
      continue;
    }
    // Public functions within this actor — preserve declaration order so that
    // an autogenerated @name getter and its set@name setter stay adjacent.
    const grouped = new Map();
    for (const fn of actor.functions) {
      if (!fn.name) continue;
      const isGetter = fn.name.startsWith('@');
      const isSetter = fn.name.startsWith('set@');
      if (!isGetter && !isSetter) continue;
      const key = fn.name;
      if (!grouped.has(key)) grouped.set(key, { isSetter, sigs: [] });
      grouped.get(key).sigs.push(formatPublicFnSig(fn));
    }
    for (const [op, { isSetter, sigs }] of grouped) {
      if (isSetter) {
        // set@name → "set name: ..."
        const bare = op.replace(/^set@/, '');
        lines.push(`set ${bare}: ${sigs.join(' | ')}`);
      } else {
        lines.push(`${op.replace(/^@/, '')}: ${sigs.join(' | ')}`);
      }
    }
  }

  if (lines.length === 0) return '{\n}';
  return `{\n  ${lines.join('\n  ')}\n}`;
}

export function extract(source) {
  if (typeof source !== 'string') {
    throw new TypeError('extract expects a string');
  }
  const tokens = tokenize(source);
  const ast = parse(tokens);
  return {
    ast,
    interface: {
      structures: [],
      service: buildServiceDocument(ast),
    },
    dependencies: (ast.dependencies || []).filter(d => d.path).map(d => d.path),
  };
}

export function compile(ast, options = {}) {
  validate(ast, options);
  const name = options.target || process.env.BREVITY_TARGET || 'js';
  const target = getTarget(name);
  if (!target) {
    throw new Error(`Unknown BREVITY_TARGET: '${name}'. Valid targets: ${getTargetNames().join(', ')}`);
  }
  return target.codegen(ast, options);
}
