const jsParity = [
  '**/__tests__/on.test.js',
  '**/__tests__/arguments.test.js',
  '**/__tests__/proc.test.js',
  '**/__tests__/structure.test.js',
  '**/__tests__/function.test.js',
  '**/__tests__/actor.test.js',
  '**/__tests__/list.test.js',
  '**/__tests__/over.test.js',
  '**/__tests__/reduce.test.js',
  '**/__tests__/if.test.js',
  '**/__tests__/ref.test.js',
  '**/__tests__/repeat_while.test.js',
  '**/__tests__/repeat_until.test.js',
  '**/__tests__/math.test.js',
  '**/__tests__/unhandled.test.js',
  '**/__tests__/assignment.test.js',
  '**/__tests__/null.test.js',
  '**/__tests__/destructure.test.js',
  '**/__tests__/type_declaration.test.js',
  '**/__tests__/type_matching.test.js',
  '**/__tests__/end_on.test.js',
  '**/__tests__/reply.test.js',
  '**/__tests__/discard.test.js',
  '**/__tests__/type_union.test.js',
  '**/__tests__/recursion.test.js',
  '**/__tests__/function_return.test.js',
  '**/__tests__/parallel_assign.test.js',
  '**/__tests__/structure_literal.test.js',
  '**/__tests__/actor_state.test.js',
  '**/__tests__/callable.test.js',
  '**/__tests__/callable_params.test.js',
  '**/__tests__/comments.test.js',
  '**/__tests__/function_params.test.js',
  '**/__tests__/literal_type_inference.test.js',
  '**/__tests__/on_params.test.js',
  '**/__tests__/output.test.js',
  '**/__tests__/proc_params.test.js',
  '**/__tests__/profile.test.js',
  '**/__tests__/restructure.test.js',
  '**/__tests__/run.test.js',
  '**/__tests__/runtime_error.test.js',
  '**/__tests__/service_manifest.test.js',
  '**/__tests__/trailing_block.test.js',
  '**/__tests__/use.test.js',
  '**/__tests__/external_send.test.js',
];

const rustParity = [
  '**/__tests__/on.test.js',
  '**/__tests__/structure.test.js',
  '**/__tests__/arguments.test.js',
  '**/__tests__/actor.test.js',
  '**/__tests__/proc.test.js',
  '**/__tests__/function.test.js',
  '**/__tests__/assignment.test.js',
  '**/__tests__/math.test.js',
  '**/__tests__/destructure.test.js',
  '**/__tests__/unhandled.test.js',
  '**/__tests__/end_on.test.js',
  '**/__tests__/reply.test.js',
  '**/__tests__/comments.test.js',
  '**/__tests__/discard.test.js',
  '**/__tests__/null.test.js',
  '**/__tests__/type_declaration.test.js',
  '**/__tests__/type_matching.test.js',
  '**/__tests__/if.test.js',
  '**/__tests__/actor_state.test.js',
  '**/__tests__/service_manifest.test.js',
  '**/__tests__/profile.test.js',
  '**/__tests__/output.test.js',
  '**/__tests__/restructure.test.js',
  '**/__tests__/run.test.js',
  '**/__tests__/parallel_assign.test.js',
  '**/__tests__/proc_params.test.js',
  '**/__tests__/type_union.test.js',
];

const erlangParity = [
  '**/__tests__/on.test.js',
  '**/__tests__/arguments.test.js',
  '**/__tests__/proc.test.js',
  '**/__tests__/structure.test.js',
  '**/__tests__/function.test.js',
  '**/__tests__/actor.test.js',
  '**/__tests__/list.test.js',
  '**/__tests__/over.test.js',
  '**/__tests__/reduce.test.js',
  '**/__tests__/if.test.js',
  '**/__tests__/ref.test.js',
  '**/__tests__/repeat_while.test.js',
  '**/__tests__/repeat_until.test.js',
  '**/__tests__/math.test.js',
  '**/__tests__/unhandled.test.js',
  '**/__tests__/assignment.test.js',
  '**/__tests__/null.test.js',
  '**/__tests__/destructure.test.js',
  '**/__tests__/type_declaration.test.js',
  '**/__tests__/type_matching.test.js',
  '**/__tests__/end_on.test.js',
  '**/__tests__/reply.test.js',
  '**/__tests__/discard.test.js',
  '**/__tests__/type_union.test.js',
  '**/__tests__/recursion.test.js',
  '**/__tests__/function_return.test.js',
  '**/__tests__/parallel_assign.test.js',
  '**/__tests__/structure_literal.test.js',
  '**/__tests__/actor_state.test.js',
  '**/__tests__/callable.test.js',
  '**/__tests__/callable_params.test.js',
  '**/__tests__/comments.test.js',
  '**/__tests__/function_params.test.js',
  '**/__tests__/literal_type_inference.test.js',
  '**/__tests__/on_params.test.js',
  '**/__tests__/output.test.js',
  '**/__tests__/proc_params.test.js',
  '**/__tests__/profile.test.js',
  '**/__tests__/restructure.test.js',
  '**/__tests__/run.test.js',
  '**/__tests__/runtime_error.test.js',
  '**/__tests__/service_manifest.test.js',
  '**/__tests__/trailing_block.test.js',
];

export default {
  projects: [
    {
      displayName: 'js',
      testEnvironment: 'node',
      transform: {},
      testMatch: jsParity,
      testPathIgnorePatterns: ['/node_modules/'],
    },
    {
      displayName: 'rust',
      testEnvironment: 'node',
      transform: {},
      testMatch: rustParity,
      testPathIgnorePatterns: ['/node_modules/'],
    },
    {
      displayName: 'erlang',
      testEnvironment: 'node',
      transform: {},
      testMatch: erlangParity,
      testPathIgnorePatterns: ['/node_modules/'],
    },
  ],
};
