// Registry of built-in Text and Blob methods, shared by parser and codegen.
// arity: [min, max] argument count (including the text/blob operand)
// returns: the Brevity type this method produces

export const TEXT_METHODS = new Map([
  ['size',          { arity: [1, 1], returns: 'Integer' }],
  ['upper',         { arity: [1, 1], returns: 'Text' }],
  ['lower',         { arity: [1, 1], returns: 'Text' }],
  ['trim',          { arity: [1, 1], returns: 'Text' }],
  ['trim_start',    { arity: [1, 1], returns: 'Text' }],
  ['trim_end',      { arity: [1, 1], returns: 'Text' }],
  ['first',         { arity: [1, 1], returns: 'Text' }],
  ['last',          { arity: [1, 1], returns: 'Text' }],
  ['repeat',        { arity: [2, 2], returns: 'Text' }],
  ['slice',         { arity: [2, 3], returns: 'Text' }],
  ['before',        { arity: [2, 2], returns: 'Text' }],
  ['after',         { arity: [2, 2], returns: 'Text' }],
  ['replace',       { arity: [3, 3], returns: 'Text' }],
  ['replace_first', { arity: [3, 3], returns: 'Text' }],
  ['reverse',       { arity: [1, 1], returns: 'Text' }],
  ['index_of',      { arity: [2, 2], returns: 'Integer' }],
  ['empty?',        { arity: [1, 1], returns: 'Boolean' }],
  ['contains',      { arity: [2, 2], returns: 'Boolean' }],
  ['starts_with',   { arity: [2, 2], returns: 'Boolean' }],
  ['ends_with',     { arity: [2, 2], returns: 'Boolean' }],
  ['split',         { arity: [2, 2], returns: 'List' }],
  ['lines',         { arity: [1, 1], returns: 'List' }],
  ['concat',        { arity: [2, 2], returns: 'Text' }],
  ['append',        { arity: [2, 2], returns: 'Text' }],
  ['at',            { arity: [2, 2], returns: 'Text' }],
]);

// Blob methods — all non-Unicode Text operations at byte level.
// Methods that return 'Text' for Text return 'Blob' for Blob.
export const BLOB_METHODS = new Map([
  ['size',          { arity: [1, 1], returns: 'Integer' }],
  ['empty?',        { arity: [1, 1], returns: 'Boolean' }],
  ['slice',         { arity: [2, 3], returns: 'Blob' }],
  ['first',         { arity: [1, 1], returns: 'Blob' }],
  ['last',          { arity: [1, 1], returns: 'Blob' }],
  ['reverse',       { arity: [1, 1], returns: 'Blob' }],
  ['repeat',        { arity: [2, 2], returns: 'Blob' }],
  ['trim',          { arity: [1, 1], returns: 'Blob' }],
  ['trim_start',    { arity: [1, 1], returns: 'Blob' }],
  ['trim_end',      { arity: [1, 1], returns: 'Blob' }],
  ['contains',      { arity: [2, 2], returns: 'Boolean' }],
  ['starts_with',   { arity: [2, 2], returns: 'Boolean' }],
  ['ends_with',     { arity: [2, 2], returns: 'Boolean' }],
  ['index_of',      { arity: [2, 2], returns: 'Integer' }],
  ['before',        { arity: [2, 2], returns: 'Blob' }],
  ['after',         { arity: [2, 2], returns: 'Blob' }],
  ['replace',       { arity: [3, 3], returns: 'Blob' }],
  ['replace_first', { arity: [3, 3], returns: 'Blob' }],
  ['split',         { arity: [2, 2], returns: 'List' }],
  ['lines',         { arity: [1, 1], returns: 'List' }],
  ['concat',        { arity: [2, 2], returns: 'Blob' }],
  ['append',        { arity: [2, 2], returns: 'Blob' }],
  ['at',            { arity: [2, 2], returns: 'Integer' }],
  ['zeros',         { arity: [1, 1], returns: 'Blob' }],
  ['from_hex',      { arity: [1, 1], returns: 'Blob' }],
  ['to_hex',        { arity: [1, 1], returns: 'Text' }],
  ['from_base64',   { arity: [1, 1], returns: 'Blob' }],
  ['to_base64',     { arity: [1, 1], returns: 'Text' }],
  ['from_utf8',     { arity: [1, 1], returns: 'Blob' }],
  ['to_utf8',       { arity: [1, 1], returns: 'Text' }],
  ['xor',           { arity: [2, 2], returns: 'Blob' }],
  ['constant_time_equals', { arity: [2, 2], returns: 'Boolean' }],
]);

// GraphemeText methods — grapheme-cluster-indexed view on Text.
export const GRAPHEME_TEXT_METHODS = new Map([
  ['size',          { arity: [1, 1], returns: 'Integer' }],
  ['empty?',        { arity: [1, 1], returns: 'Boolean' }],
  ['slice',         { arity: [2, 3], returns: 'GraphemeText' }],
  ['first',         { arity: [1, 1], returns: 'GraphemeText' }],
  ['last',          { arity: [1, 1], returns: 'GraphemeText' }],
  ['reverse',       { arity: [1, 1], returns: 'GraphemeText' }],
  ['repeat',        { arity: [2, 2], returns: 'GraphemeText' }],
  ['trim',          { arity: [1, 1], returns: 'GraphemeText' }],
  ['trim_start',    { arity: [1, 1], returns: 'GraphemeText' }],
  ['trim_end',      { arity: [1, 1], returns: 'GraphemeText' }],
  ['contains',      { arity: [2, 2], returns: 'Boolean' }],
  ['starts_with',   { arity: [2, 2], returns: 'Boolean' }],
  ['ends_with',     { arity: [2, 2], returns: 'Boolean' }],
  ['index_of',      { arity: [2, 2], returns: 'Integer' }],
  ['before',        { arity: [2, 2], returns: 'GraphemeText' }],
  ['after',         { arity: [2, 2], returns: 'GraphemeText' }],
  ['replace',       { arity: [3, 3], returns: 'GraphemeText' }],
  ['replace_first', { arity: [3, 3], returns: 'GraphemeText' }],
  ['split',         { arity: [2, 2], returns: 'List' }],
  ['lines',         { arity: [1, 1], returns: 'List' }],
  ['concat',        { arity: [2, 2], returns: 'GraphemeText' }],
  ['append',        { arity: [2, 2], returns: 'GraphemeText' }],
  ['at',            { arity: [2, 2], returns: 'Text' }],
]);
